;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		__isr_irq
	.export		__isr_nmi
	.export		__isr_break
	.export		_main

; ---------------------------------------------------------------
; void __near__ _isr_irq (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__isr_irq: near

.segment	"CODE"

	rts

.endproc

; ---------------------------------------------------------------
; void __near__ _isr_nmi (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__isr_nmi: near

.segment	"CODE"

	rts

.endproc

; ---------------------------------------------------------------
; void __near__ _isr_break (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__isr_break: near

.segment	"CODE"

	rts

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	txa
	rts

.endproc

